# Site settings
title: Data viz utils
description: Functions for data visualization in matplotlib
keywords: Visualization, Data, Matplotlib
author: Chandan Singh
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
